#include <arinc653/types.h>
#include <arinc653/event.h>
#include <assert.h>
#include <arinc653/time.h>
#include "deployment.h"
#include "subprograms.h"
/**************************************************** */
/*  This file was automatically generated by Ocarina  */
/*  Working Copy from r9873d8b0 */
/*  Do NOT hand-modify this file, as your             */
/*  changes will be lost when you re-run Ocarina      */
/**************************************************** */
/*  Periodic task : thr1 */
extern EVENT_ID_TYPE input_id;
void* thr1_job (void)
{

  RETURN_CODE_TYPE ret;
  while (1)
  {
    /*  Send the OUT ports */
    SET_EVENT (input_id, &(ret));
    ASSERT_RET(ret);
    PERIODIC_WAIT (&(ret));
  }
}

/*  Periodic task : thr2 */
extern EVENT_ID_TYPE input_id;
void* thr2_job (void)
{

  RETURN_CODE_TYPE ret;
  while (1)
  {
    /*  Get the IN ports values */
    WAIT_EVENT (input_id, 0, &(ret));
    /* :: Yes if commentary :: */
    if (ret == NO_ERROR)
    {
          arinc653_testevents__spg_receive_event ();

    }
    PERIODIC_WAIT (&(ret));
  }
}


