#include <arinc653/event.h>
#include "deployment.h"
#include <arinc653/types.h>
/**************************************************** */
/*  This file was automatically generated by Ocarina  */
/*  Working Copy from r9873d8b0 */
/*  Do NOT hand-modify this file, as your             */
/*  changes will be lost when you re-run Ocarina      */
/**************************************************** */
EVENT_ID_TYPE input_id;
char* pok_arinc653_events_names[POK_CONFIG_ARINC653_NB_EVENTS] = {"input"};

