#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
/**************************************************** */

/*  This file was automatically generated by Ocarina  */

/*  Working Copy from r9873d8b0 */

/*  Do NOT hand-modify this file, as your             */

/*  changes will be lost when you re-run Ocarina      */

/**************************************************** */

#define OCARINA_RUNTIME_POK 1

#define POK_GENERATED_CODE 1

#define POK_NEEDS_CONSOLE 1

#define POK_NEEDS_LIBC_STDIO 1

#define POK_CONFIG_NB_THREADS 3

#define POK_CONFIG_NB_EVENTS 1

#define POK_NEEDS_EVENTS 1

#define POK_CONFIG_STACKS_SIZE 16384

#define POK_CONFIG_ARINC653_NB_EVENTS 1

#define POK_NEEDS_ARINC653_TIME 1

#define POK_NEEDS_ARINC653_PROCESS 1

#define POK_NEEDS_ARINC653_EVENT 1

#define POK_NEEDS_ARINC653_PARTITION 1

#endif
