#include "activity.h"
#include "gtypes.h"
#include <arinc653/types.h>
#include "deployment.h"
#include <arinc653/process.h>
#include <assert.h>
#include <arinc653/event.h>
#include <arinc653/partition.h>
/**************************************************** */
/*  This file was automatically generated by Ocarina  */
/*  Working Copy from r9873d8b0 */
/*  Do NOT hand-modify this file, as your             */
/*  changes will be lost when you re-run Ocarina      */
/**************************************************** */
PROCESS_ID_TYPE arinc_threads[POK_CONFIG_NB_THREADS];
extern EVENT_ID_TYPE input_id;
int main (void)
{

  PROCESS_ATTRIBUTE_TYPE tattr;
  RETURN_CODE_TYPE ret;
  tattr.ENTRY_POINT = thr1_job;
  tattr.BASE_PRIORITY = 2;
  tattr.DEADLINE = 1000;
  tattr.PERIOD = 1000;
  tattr.STACK_SIZE = 4096;
  tattr.TIME_CAPACITY = 500;
  CREATE_PROCESS (&(tattr), &(arinc_threads[1]), &(ret));
  START (arinc_threads[1], &(ret));
  ASSERT_RET(ret);
  /*  This thread was mapped from a thread component containedin this  */
  /*  process. The function it executes is also generatedin the file  */
  /*  activity.c. */
  CREATE_EVENT ("input", &(input_id), &(ret));
  ASSERT_RET(ret);
  tattr.ENTRY_POINT = thr2_job;
  tattr.BASE_PRIORITY = 1;
  tattr.DEADLINE = 1000;
  tattr.PERIOD = 1000;
  tattr.STACK_SIZE = 4096;
  tattr.TIME_CAPACITY = 500;
  CREATE_PROCESS (&(tattr), &(arinc_threads[2]), &(ret));
  START (arinc_threads[2], &(ret));
  ASSERT_RET(ret);
  /*  This thread was mapped from a thread component containedin this  */
  /*  process. The function it executes is also generatedin the file  */
  /*  activity.c. */
  SET_PARTITION_MODE (NORMAL, &(ret));
  /*  Now, we created all resources of the process. Consequently,this thread  */
  /*  will not be used any more and it will be keptin a dormant state. By  */
  /*  doing that, we also allow one morethread in this partition */
  return (0);
}


