#ifndef __OCARINA_GENERATED_SUBPROGRAMS_H_
#define __OCARINA_GENERATED_SUBPROGRAMS_H_ 
/**************************************************** */

/*  This file was automatically generated by Ocarina  */

/*  Working Copy from r9873d8b0 */

/*  Do NOT hand-modify this file, as your             */

/*  changes will be lost when you re-run Ocarina      */

/**************************************************** */

void arinc653_testevents__spg_receive_event (void);

#endif
